name: Test setup-jfrog-cli with oidc

on:
  push:
    branches:
      - main

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
  contents: read

jobs:
  setup-cli:
    runs-on: ubuntu-latest
    env:
      JF_URL: ${{ vars.JF_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Replace with your desired Java version
          distribution: 'temurin'

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core @actions/http-client

      - name: Install JFrog CLI
        uses: eranturgeman/setup-jfrog-cli@adding-oidc-auth
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          aud: https://github.com/eranturgeman


      - name: Test JF CLI
        run: |
          jf c show
          jf rt ping
        
